const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.resolveTargetQuery(.{
        .cpu_arch = .aarch64,
        .cpu_model = .{ .explicit = &std.Target.arm.cpu.cortex_a55 },
        .os_tag = .freestanding,
        .abi = .none,
    });

    const libc = b.addStaticLibrary(.{
        .name = "c",
        .target = target,
        .optimize = b.standardOptimizeOption(.{}),
    });

    libc.addCSourceFiles(.{
        .files = &.{
            "newlib/libc/string/wmemset.c",
            "newlib/libc/string/bzero.c",
            "newlib/libc/string/strnstr.c",
            "newlib/libc/string/strncpy.c",
            "newlib/libc/string/index.c",
            "newlib/libc/string/wmemchr.c",
            "newlib/libc/string/wcsxfrm_l.c",
            "newlib/libc/string/memmove.c",
            "newlib/libc/string/strxfrm.c",
            "newlib/libc/string/strupr.c",
            "newlib/libc/string/wcwidth.c",
            "newlib/libc/string/wmempcpy.c",
            "newlib/libc/string/wcpncpy.c",
            "newlib/libc/string/wcscasecmp_l.c",
            "newlib/libc/string/wcsdup.c",
            "newlib/libc/string/u_strerr.c",
            "newlib/libc/string/wcspbrk.c",
            "newlib/libc/string/strncasecmp.c",
            "newlib/libc/string/wcsncmp.c",
            "newlib/libc/string/timingsafe_memcmp.c",
            "newlib/libc/string/wcsrchr.c",
            "newlib/libc/string/strcpy.c",
            "newlib/libc/string/wmemmove.c",
            "newlib/libc/string/strrchr.c",
            "newlib/libc/string/strncat.c",
            "newlib/libc/string/wmemcmp.c",
            "newlib/libc/string/stpncpy.c",
            "newlib/libc/string/strsep.c",
            "newlib/libc/string/wcsncasecmp_l.c",
            "newlib/libc/string/strcat.c",
            "newlib/libc/string/strchr.c",
            "newlib/libc/string/fls.c",
            "newlib/libc/string/strtok_r.c",
            "newlib/libc/string/memrchr.c",
            "newlib/libc/string/mempcpy.c",
            "newlib/libc/string/memmem.c",
            "newlib/libc/string/flsll.c",
            "newlib/libc/string/strcoll.c",
            "newlib/libc/string/wcscmp.c",
            "newlib/libc/string/strcmp.c",
            "newlib/libc/string/strlwr.c",
            "newlib/libc/string/wcschr.c",
            "newlib/libc/string/strpbrk.c",
            "newlib/libc/string/strerror_r.c",
            "newlib/libc/string/strspn.c",
            "newlib/libc/string/explicit_bzero.c",
            "newlib/libc/string/wcsspn.c",
            "newlib/libc/string/wcsxfrm.c",
            "newlib/libc/string/wcsncpy.c",
            "newlib/libc/string/swab.c",
            "newlib/libc/string/ffsl.c",
            "newlib/libc/string/strlen.c",
            "newlib/libc/string/strcspn.c",
            "newlib/libc/string/timingsafe_bcmp.c",
            "newlib/libc/string/strxfrm_l.c",
            "newlib/libc/string/wcscasecmp.c",
            "newlib/libc/string/wcslcpy.c",
            "newlib/libc/string/strsignal.c",
            "newlib/libc/string/wcsstr.c",
            "newlib/libc/string/wcsncat.c",
            "newlib/libc/string/strchrnul.c",
            "newlib/libc/string/strcasecmp_l.c",
            "newlib/libc/string/wmemcpy.c",
            "newlib/libc/string/memcmp.c",
            "newlib/libc/string/memchr.c",
            "newlib/libc/string/memccpy.c",
            "newlib/libc/string/strcasestr.c",
            "newlib/libc/string/gnu_basename.c",
            "newlib/libc/string/strncmp.c",
            "newlib/libc/string/ffsll.c",
            "newlib/libc/string/strverscmp.c",
            "newlib/libc/string/rawmemchr.c",
            "newlib/libc/string/wcslen.c",
            "newlib/libc/string/wcsnlen.c",
            "newlib/libc/string/strtok.c",
            "newlib/libc/string/strdup.c",
            "newlib/libc/string/wcstok.c",
            "newlib/libc/string/strnlen.c",
            "newlib/libc/string/strerror.c",
            "newlib/libc/string/wcscat.c",
            "newlib/libc/string/strncasecmp_l.c",
            "newlib/libc/string/memcpy.c",
            "newlib/libc/string/bcmp.c",
            "newlib/libc/string/wcscpy.c",
            "newlib/libc/string/strlcpy.c",
            "newlib/libc/string/strlcat.c",
            "newlib/libc/string/wcscspn.c",
            "newlib/libc/string/wcscoll_l.c",
            "newlib/libc/string/wcscoll.c",
            "newlib/libc/string/stpcpy.c",
            "newlib/libc/string/wcsncasecmp.c",
            "newlib/libc/string/strstr.c",
            "newlib/libc/string/rindex.c",
            "newlib/libc/string/bcopy.c",
            "newlib/libc/string/strcasecmp.c",
            "newlib/libc/string/memset.c",
            "newlib/libc/string/xpg_strerror_r.c",
            "newlib/libc/string/wcswidth.c",
            "newlib/libc/string/wcslcat.c",
            "newlib/libc/string/strcoll_l.c",
            "newlib/libc/string/strndup.c",
            "newlib/libc/string/flsl.c",
            "newlib/libc/string/wcpcpy.c",
            "newlib/libc/argz/argz_stringify.c",
            "newlib/libc/stdlib/atoll.c",
            "newlib/libc/stdlib/mbrtowc.c",
            "newlib/libc/stdlib/wcstoimax.c",
            // "newlib/libc/stdlib/malloc-malloc.c",
            "newlib/libc/stdlib/drand48.c",
            "newlib/libc/stdlib/strtod.c",
            "newlib/libc/stdlib/pico-onexit.c",
            "newlib/libc/stdlib/strtoimax.c",
            // "newlib/libc/stdlib/malloc-free.c",
            "newlib/libc/stdlib/nano-malloc-free.c",
            "newlib/libc/stdlib/utoa.c",
            "newlib/libc/stdlib/strtold.c",
            "newlib/libc/stdlib/assert.c",
            // "newlib/libc/stdlib/malloc-valloc.c",
            "newlib/libc/stdlib/rand.c",
            "newlib/libc/stdlib/mrand48.c",
            "newlib/libc/stdlib/labs.c",
            "newlib/libc/stdlib/lcong48.c",
            "newlib/libc/stdlib/nano-malloc-realloc.c",
            "newlib/libc/stdlib/nano-malloc-malloc_stats.c",
            "newlib/libc/stdlib/setenv.c",
            "newlib/libc/stdlib/mbtowc.c",
            "newlib/libc/stdlib/arc4random.c",
            "newlib/libc/stdlib/pico-exit.c",
            "newlib/libc/stdlib/sb_charsets.c",
            "newlib/libc/stdlib/itoa.c",
            "newlib/libc/stdlib/atoff.c",
            "newlib/libc/stdlib/wcstol.c",
            "newlib/libc/stdlib/jrand48.c",
            "newlib/libc/stdlib/wcstoll.c",
            "newlib/libc/stdlib/wcsrtombs.c",
            "newlib/libc/stdlib/wctob.c",
            // "newlib/libc/stdlib/cxa_atexit.c",
            "newlib/libc/stdlib/wcstold.c",
            "newlib/libc/stdlib/srand48.c",
            // "newlib/libc/stdlib/quick_exit.c",
            "newlib/libc/stdlib/wcstoll_r.c",
            "newlib/libc/stdlib/nano-malloc-calloc.c",
            "newlib/libc/stdlib/rpmatch.c",
            "newlib/libc/stdlib/a64l.c",
            "newlib/libc/stdlib/nano-malloc-getpagesize.c",
            "newlib/libc/stdlib/imaxabs.c",
            "newlib/libc/stdlib/strtodg.c",
            "newlib/libc/stdlib/nano-malloc-mallinfo.c",
            "newlib/libc/stdlib/wcrtomb.c",
            "newlib/libc/stdlib/nano-malloc-mallopt.c",
            // "newlib/libc/stdlib/on_exit.c",
            "newlib/libc/stdlib/srand.c",
            "newlib/libc/stdlib/strtol.c",
            "newlib/libc/stdlib/assert_func.c",
            "newlib/libc/stdlib/wcstod.c",
            "newlib/libc/stdlib/atol.c",
            "newlib/libc/stdlib/mbsrtowcs.c",
            // "newlib/libc/stdlib/exit.c",
            "newlib/libc/stdlib/ecvtbuf.c",
            "newlib/libc/stdlib/btowc.c",
            "newlib/libc/stdlib/putenv.c",
            "newlib/libc/stdlib/mbtowc_r.c",
            "newlib/libc/stdlib/reallocarray.c",
            "newlib/libc/stdlib/gdtoa-gethex.c",
            "newlib/libc/stdlib/getenv_r.c",
            "newlib/libc/stdlib/mprec.c",
            "newlib/libc/stdlib/getsubopt.c",
            "newlib/libc/stdlib/wctomb.c",
            "newlib/libc/stdlib/aligned_alloc.c",
            "newlib/libc/stdlib/dtoa.c",
            "newlib/libc/stdlib/mbstowcs.c",
            "newlib/libc/stdlib/seed48.c",
            // "newlib/libc/stdlib/malloc-malloc_usable_size.c",
            "newlib/libc/stdlib/random.c",
            "newlib/libc/stdlib/nano-malloc-posix_memalign.c",
            "newlib/libc/stdlib/wcstoumax.c",
            "newlib/libc/stdlib/erand48.c",
            "newlib/libc/stdlib/wcstoull.c",
            "newlib/libc/stdlib/arc4random_uniform.c",
            "newlib/libc/stdlib/mstats.c",
            "newlib/libc/stdlib/strtoul.c",
            // "newlib/libc/stdlib/malloc-mallopt.c",
            "newlib/libc/stdlib/system.c",
            "newlib/libc/stdlib/wcstoull_r.c",
            "newlib/libc/stdlib/wcstombs.c",
            "newlib/libc/stdlib/mbrlen.c",
            "newlib/libc/stdlib/getopt.c",
            "newlib/libc/stdlib/lldiv.c",
            // "newlib/libc/stdlib/calloc.c",
            "newlib/libc/stdlib/strtorx.c",
            // "newlib/libc/stdlib/atexit.c",
            "newlib/libc/stdlib/lrand48.c",
            "newlib/libc/stdlib/wctomb_r.c",
            "newlib/libc/stdlib/nano-malloc-memalign.c",
            "newlib/libc/stdlib/nano-malloc-valloc.c",
            // "newlib/libc/stdlib/__atexit.c",
            "newlib/libc/stdlib/pico-cxa-atexit.c",
            "newlib/libc/stdlib/environ.c",
            "newlib/libc/stdlib/div.c",
            "newlib/libc/stdlib/strtoll.c",
            "newlib/libc/stdlib/strtoull.c",
            "newlib/libc/stdlib/wcstoul.c",
            "newlib/libc/stdlib/abs.c",
            "newlib/libc/stdlib/_Exit.c",
            // "newlib/libc/stdlib/malloc-memalign.c",
            "newlib/libc/stdlib/assert_no_arg.c",
            "newlib/libc/stdlib/mbsnrtowcs.c",
            "newlib/libc/stdlib/imaxdiv.c",
            "newlib/libc/stdlib/getenv.c",
            "newlib/libc/stdlib/nano-malloc-pvalloc.c",
            "newlib/libc/stdlib/atof.c",
            "newlib/libc/stdlib/strtoumax.c",
            "newlib/libc/stdlib/atoi.c",
            "newlib/libc/stdlib/l64a.c",
            "newlib/libc/stdlib/efgcvt.c",
            // "newlib/libc/stdlib/malloc-pvalloc.c",
            "newlib/libc/stdlib/reallocf.c",
            "newlib/libc/stdlib/ldtoa.c",
            "newlib/libc/stdlib/rand_r.c",
            // "newlib/libc/stdlib/malloc-calloc.c",
            "newlib/libc/stdlib/wcsnrtombs.c",
            "newlib/libc/stdlib/nano-malloc-malloc_usable_size.c",
            // "newlib/libc/stdlib/malloc-mallinfo.c",
            "newlib/libc/stdlib/srandom.c",
            "newlib/libc/stdlib/mbsinit.c",
            "newlib/libc/stdlib/nano-mallocr.c",
            "newlib/libc/stdlib/nano-malloc-cfree.c",
            // "newlib/libc/stdlib/cxa_finalize.c",
            // "newlib/libc/stdlib/__call_atexit.c",
            "newlib/libc/stdlib/rand48.c",
            "newlib/libc/stdlib/abort.c",
            "newlib/libc/stdlib/pico-atexit.c",
            // "newlib/libc/stdlib/malloc-cfree.c",
            "newlib/libc/stdlib/llabs.c",
            "newlib/libc/stdlib/eprintf.c",
            // "newlib/libc/stdlib/malloc-realloc.c",
            // "newlib/libc/stdlib/malloc-malloc_stats.c",
            "newlib/libc/stdlib/gdtoa-hexnan.c",
            // "newlib/libc/stdlib/mallocr.c",
            "newlib/libc/stdlib/mblen.c",
            "newlib/libc/stdlib/ldiv.c",
            "newlib/libc/stdlib/nrand48.c",
            "newlib/libc/stdlib/nano-malloc-malloc.c",
            "newlib/libc/errno/errno.c",
            "newlib/libc/ctype/ctype_.c",
            "newlib/libc/tinystdio/asprintf.c",
            "newlib/libc/tinystdio/bufio.c",
            "newlib/libc/tinystdio/clearerr.c",
            "newlib/libc/tinystdio/dtox_engine.c",
            "newlib/libc/tinystdio/ecvt_r.c",
            "newlib/libc/tinystdio/ecvt.c",
            "newlib/libc/tinystdio/ecvtf_r.c",
            "newlib/libc/tinystdio/ecvtf.c",
            "newlib/libc/tinystdio/ecvtl_r.c",
            "newlib/libc/tinystdio/ecvtl.c",
            "newlib/libc/tinystdio/fcvt.c",
            "newlib/libc/tinystdio/fcvt_r.c",
            "newlib/libc/tinystdio/fcvtf.c",
            "newlib/libc/tinystdio/fcvtf_r.c",
            "newlib/libc/tinystdio/fcvtl.c",
            "newlib/libc/tinystdio/fcvtl_r.c",
            "newlib/libc/tinystdio/gcvt.c",
            "newlib/libc/tinystdio/gcvtf.c",
            "newlib/libc/tinystdio/gcvtl.c",
            "newlib/libc/tinystdio/fclose.c",
            "newlib/libc/tinystdio/fdevopen.c",
            "newlib/libc/tinystdio/feof.c",
            "newlib/libc/tinystdio/ferror.c",
            "newlib/libc/tinystdio/fflush.c",
            "newlib/libc/tinystdio/fgetc.c",
            "newlib/libc/tinystdio/fgets.c",
            "newlib/libc/tinystdio/fgetwc.c",
            "newlib/libc/tinystdio/fgetws.c",
            "newlib/libc/tinystdio/fileno.c",
            "newlib/libc/tinystdio/filestrget.c",
            "newlib/libc/tinystdio/filestrput.c",
            "newlib/libc/tinystdio/filestrputalloc.c",
            "newlib/libc/tinystdio/filewstrget.c",
            "newlib/libc/tinystdio/fmemopen.c",
            "newlib/libc/tinystdio/fprintf.c",
            "newlib/libc/tinystdio/fputc.c",
            "newlib/libc/tinystdio/fputs.c",
            "newlib/libc/tinystdio/fputwc.c",
            "newlib/libc/tinystdio/fputws.c",
            "newlib/libc/tinystdio/fread.c",
            "newlib/libc/tinystdio/fscanf.c",
            "newlib/libc/tinystdio/fseek.c",
            "newlib/libc/tinystdio/fseeko.c",
            "newlib/libc/tinystdio/ftell.c",
            "newlib/libc/tinystdio/ftello.c",
            "newlib/libc/tinystdio/ftox_engine.c",
            "newlib/libc/tinystdio/fwide.c",
            "newlib/libc/tinystdio/fwrite.c",
            "newlib/libc/tinystdio/fwprintf.c",
            "newlib/libc/tinystdio/fwscanf.c",
            "newlib/libc/tinystdio/getchar.c",
            "newlib/libc/tinystdio/getdelim.c",
            "newlib/libc/tinystdio/getline.c",
            "newlib/libc/tinystdio/gets.c",
            "newlib/libc/tinystdio/getwchar.c",
            "newlib/libc/tinystdio/ldtoa_engine.c",
            "newlib/libc/tinystdio/ldtox_engine.c",
            "newlib/libc/tinystdio/matchcaseprefix.c",
            "newlib/libc/tinystdio/mktemp.c",
            "newlib/libc/tinystdio/perror.c",
            "newlib/libc/tinystdio/printf.c",
            "newlib/libc/tinystdio/putchar.c",
            "newlib/libc/tinystdio/puts.c",
            "newlib/libc/tinystdio/putwchar.c",
            "newlib/libc/tinystdio/remove.c",
            "newlib/libc/tinystdio/rewind.c",
            "newlib/libc/tinystdio/scanf.c",
            "newlib/libc/tinystdio/setbuf.c",
            "newlib/libc/tinystdio/setbuffer.c",
            "newlib/libc/tinystdio/setlinebuf.c",
            "newlib/libc/tinystdio/setvbuf.c",
            "newlib/libc/tinystdio/sflags.c",
            "newlib/libc/tinystdio/snprintf.c",
            "newlib/libc/tinystdio/sprintf.c",
            "newlib/libc/tinystdio/snprintfd.c",
            "newlib/libc/tinystdio/snprintff.c",
            "newlib/libc/tinystdio/sprintff.c",
            "newlib/libc/tinystdio/sprintfd.c",
            "newlib/libc/tinystdio/sscanf.c",
            "newlib/libc/tinystdio/strfromf.c",
            "newlib/libc/tinystdio/strfromd.c",
            "newlib/libc/tinystdio/strfroml.c",
            "newlib/libc/tinystdio/strtof.c",
            "newlib/libc/tinystdio/strtof_l.c",
            "newlib/libc/tinystdio/strtod.c",
            "newlib/libc/tinystdio/strtod_l.c",
            "newlib/libc/tinystdio/strtoimax.c",
            "newlib/libc/tinystdio/strtoumax.c",
            "newlib/libc/tinystdio/strtol.c",
            "newlib/libc/tinystdio/strtoll.c",
            "newlib/libc/tinystdio/strtoul.c",
            "newlib/libc/tinystdio/strtoull.c",
            "newlib/libc/tinystdio/strtol_l.c",
            "newlib/libc/tinystdio/strtoll_l.c",
            "newlib/libc/tinystdio/strtoul_l.c",
            "newlib/libc/tinystdio/strtoull_l.c",
            "newlib/libc/tinystdio/swprintf.c",
            "newlib/libc/tinystdio/swscanf.c",
            "newlib/libc/tinystdio/tmpnam.c",
            "newlib/libc/tinystdio/tmpfile.c",
            "newlib/libc/tinystdio/ungetc.c",
            "newlib/libc/tinystdio/ungetwc.c",
            "newlib/libc/tinystdio/vasprintf.c",
            "newlib/libc/tinystdio/vffprintf.c",
            "newlib/libc/tinystdio/vfiprintf.c",
            "newlib/libc/tinystdio/vflprintf.c",
            "newlib/libc/tinystdio/vfmprintf.c",
            "newlib/libc/tinystdio/vfprintf.c",
            "newlib/libc/tinystdio/vfscanf.c",
            "newlib/libc/tinystdio/vffscanf.c",
            "newlib/libc/tinystdio/vfiscanf.c",
            "newlib/libc/tinystdio/vflscanf.c",
            "newlib/libc/tinystdio/vfmscanf.c",
            "newlib/libc/tinystdio/vfwprintf.c",
            "newlib/libc/tinystdio/vfwscanf.c",
            "newlib/libc/tinystdio/vprintf.c",
            "newlib/libc/tinystdio/vscanf.c",
            "newlib/libc/tinystdio/vsscanf.c",
            "newlib/libc/tinystdio/vsnprintf.c",
            "newlib/libc/tinystdio/vsprintf.c",
            "newlib/libc/tinystdio/vswprintf.c",
            "newlib/libc/tinystdio/vswscanf.c",
            "newlib/libc/tinystdio/vwprintf.c",
            "newlib/libc/tinystdio/vwscanf.c",
            "newlib/libc/tinystdio/wprintf.c",
            "newlib/libc/tinystdio/wscanf.c",
            "newlib/libc/tinystdio/fopen.c",
            "newlib/libc/tinystdio/fdopen.c",
            "newlib/libc/signal/signal.c",
            // "newlib/libc/signal/psignal.c",
            "newlib/libc/reent/reent.c",
            "newlib/libc/locale/duplocale.c",
            "newlib/libc/locale/freelocale.c",
            "newlib/libc/locale/locale.c",
            "newlib/libc/locale/localeconv.c",
            "newlib/libc/locale/lnumeric.c",
            "newlib/libc/locale/newlocale.c",
            "newlib/libc/locale/timelocal.c",
            "newlib/libc/locale/uselocale.c",
            "newlib/libc/locale/lctype.c",
            "newlib/libc/locale/lmessages.c",
            "newlib/libc/locale/lmonetary.c",
            "newlib/libc/locale/nl_langinfo.c",
            // We want to use our defined __heap_start and __heap_end and so
            // we need to compile these source files as it contains sbrk that
            // uses those symbols.
            "newlib/libc/picolib/picosbrk.c",
            "newlib/libc/picolib/dso_handle.c",
            "newlib/libc/picolib/getauxval.c",
            "extensions/bind.c",
            "extensions/getpid.c",
            "extensions/clock_gettime.c",
            "extensions/getuid.c",
            "extensions/getgid.c",
            "extensions/close.c",
            "extensions/ntohl.c",
            "extensions/htonl.c",
            "extensions/internal/syscall_ret.c",
            "newlib/libc/ctype/isxdigit.c",
            "newlib/libc/time/time.c",
        },
        // @ivanv: the format is dependent on picolibc.h
        .flags = &.{
            "-DFORMAT_DEFAULT_MINIMAL",
        },
    });
    libc.addIncludePath(.{ .path = "newlib/libc/include" });
    libc.addIncludePath(.{ .path = "newlib/libc/stdlib" });
    libc.addIncludePath(.{ .path = "newlib/libc/signal" });
    libc.addIncludePath(.{ .path = "newlib/libc/sys" });
    libc.addIncludePath(.{ .path = "newlib/libc/locale" });
    libc.addIncludePath(.{ .path = "extensions/include" });
    libc.addIncludePath(.{ .path = "extensions/internal" });
    const tinystdio = true;
    if (tinystdio) {
        libc.addIncludePath(.{ .path = "newlib/libc/tinystdio" });
    } else {
        libc.addIncludePath(.{ .path = "newlib/libc/stdio" });
    }
    // @ivanv: hack until we auto-generate picolibc.h from picolibc.h.in
    libc.addIncludePath(.{ .path = "" });

    b.installArtifact(libc);
}
